// Generated by apps/api/scripts/generate_template_narration.py — do not edit.
//
// One entry per recorded line, carrying the text it was made from so the
// player can stay silent when a parameter edit (or an un-recorded narration
// change) has moved that step's wording away from the audio.

export interface RecordedNarrationEntry {
  step_id: string;
  file: string;
  text: string;
}

export const RECORDED_NARRATION_VOICE = "zh_male_m191_uranus_bigtts";

export const RECORDED_NARRATION: Readonly<
  Record<string, readonly RecordedNarrationEntry[]>
> = Object.freeze({
  "bst-search": [
    { step_id: "bst-intro", file: "bst-intro.mp3", text: "这棵树按 8、3、10、1、6、14、4、7、13 的顺序依次插入建成，根是 8。任务是查找 7：从根出发，每到一个节点只做一次比较，就能决定往左还是往右，不必看另一半子树。" },
    { step_id: "bst-property", file: "bst-property.mp3", text: "二叉搜索树的性质：任意节点的左子树所有值都小于它，右子树所有值都大于它。以根 8 为例，左子树是 1、3、4、6、7，右子树是 10、13、14。画面里节点的横坐标就是中序位置，所以性质在左右方向上直接可见。" },
    { step_id: "bst-compare-8", file: "bst-compare-8.mp3", text: "来到节点 8，目标 7 小于 8，所以整棵右子树都不用看，沿左孩子进入 3。这是第 1 次比较。" },
    { step_id: "bst-compare-3", file: "bst-compare-3.mp3", text: "来到节点 3，目标 7 大于 3，所以整棵左子树都不用看，沿右孩子进入 6。这是第 2 次比较。" },
    { step_id: "bst-compare-6", file: "bst-compare-6.mp3", text: "来到节点 6，目标 7 大于 6，所以整棵左子树都不用看，沿右孩子进入 7。这是第 3 次比较。" },
    { step_id: "bst-compare-7", file: "bst-compare-7.mp3", text: "来到节点 7，目标 7 正好等于它，查找结束。这是第 4 次比较，走过的路径依次是 8、3、6、7。" },
    { step_id: "bst-result", file: "bst-result.mp3", text: "目标 7 就在路径末端。整条路径依次经过 8、3、6、7，只有 4 个节点，其余 5 个节点一次都没有访问。" },
    { step_id: "bst-complexity", file: "bst-complexity.mp3", text: "这次查找比较了 4 次，正好是路径上的节点数。任何一次查找都不会超过树高 4，所以复杂度是 O(h)。树越平衡，h 越接近 log₂n；如果按有序序列插入，树会退化成链，h 变成 n——这正是平衡树要解决的问题。" },
  ],
  "competition-exclusion": [
    { step_id: "comp-alone", file: "comp-alone.mp3", text: "1934 年，Gause 把两种草履虫分别放进 0.5 毫升培养液，每天投喂定量细菌、每天计数。双小核草履虫稳稳爬到约 105 的平台，大草履虫爬到约 64——各是一条标准的 logistic 曲线，各有各的 K。上一课的方程，在显微镜下活着。" },
    { step_id: "comp-together", file: "comp-together.mp3", text: "再把它们放进同一瓶，食物不变。前一周相安无事——大草履虫第 8 天冲到约 24，好像也要起飞。然后曲线调头：第 16 天跌回 15，第 24 天只剩约 8，一路滑向清零。它单独活得好好的，没有谁吃谁，为什么一起养就消失？" },
    { step_id: "comp-equations", file: "comp-equations.mp3", text: "武器不是牙齿，是同一碗饭。在各自的 logistic 里，给对方留一个位置：α 表示一个大草履虫吃掉的资源折合多少个双小核，β 反过来。α、β 是竞争的汇率。这里 α=1.5——大草履虫个头大、吃得多，每一个都顶一个半对手；β=0.7。方程写完，结局就已经写完，只是我们还没看出来。" },
    { step_id: "comp-isoclines", file: "comp-isoclines.mp3", text: "想看清结局，去相平面：横轴 N₁，纵轴 N₂。令 dN₁/dt=0，得到一条直线 N₁+αN₂=K₁——线内 N₁ 还能涨，线外必须跌；大草履虫也有自己的停线 βN₁+N₂=K₂。两条线的相对位置决定一切。当前 α=1.5、β=0.7：双小核草履虫稳赢。拖动右侧的 α、β，亲手把两条线摆出别的位置。" },
    { step_id: "comp-exclusion", file: "comp-exclusion.mp3", text: "Gause 场景里（α=1.5、β=0.7），双小核的停线整个罩在大草履虫的停线外面：平面上存在一条走廊，那里双小核还能涨、大草履虫已经必须跌。轨迹被推着沿对手的停线滑向 (105, 0)——大草履虫的清零不是意外，是几何。这就是竞争排斥原理：需求完全重叠的两个物种，不能长期共存。" },
    { step_id: "comp-coexist", file: "comp-coexist.mp3", text: "把竞争调弱：α=0.6、β=0.7 换成 β=0.4——每个物种压自己都比压对方狠。两条停线交叉，交点 (88, 29) 变成所有轨迹的归宿：从哪个角落出发都收进去。共存的判据由此而来：种内竞争强于种间竞争。写成代数就是 α<K₁/K₂=1.64 且 β<K₂/K₁=0.61，两条同时成立。" },
    { step_id: "comp-founder", file: "comp-founder.mp3", text: "还有一种排布：α=1.8、β=0.9，双方压对方都比压自己狠。停线仍然交叉，但交点 (16, 49) 是个鞍点——理论上能停住，任何风吹草动都会滑落。从 (40,10) 出发，双小核赢；从 (10,40) 出发，大草履虫赢。同样的规则，不同的开局，相反的结局：历史也被写进了方程。" },
    { step_id: "comp-bursaria", file: "comp-bursaria.mp3", text: "Gause 还做了一组常被忽略的对照：把大草履虫换成绿草履虫，再混养。这次没有清零——双小核占据上层水体吃悬浮细菌，绿草履虫沉到瓶底吃酵母，两条曲线都停在了正数上。同一间瓶子，两份工作。竞争排斥原理因此有了下半句：完全重叠的生态位不能共存，而差异——哪怕只是一瓶水的上下——就是共存的通行证。" },
    { step_id: "comp-sandbox", file: "comp-sandbox.mp3", text: "α、β、两个起点，全部归你。当前 α=1.5、β=0.7，判定：双小核草履虫稳赢。读图口诀：先看两条停线交不交叉，交叉再问谁让着自己。把 α 推过 1.64、β 推过 0.61，四种世界依次路过。下一课离开双人对局，去数一整座岛的物种。" },
  ],
  "dijkstra": [
    { step_id: "dijkstra-intro", file: "dijkstra-intro.mp3", text: "图有 6 个节点、9 条带权边，要求 A 到每个节点的最短距离。初始化：A 的距离是 0，其余都是无穷大。Dijkstra 的核心是贪心：每次把当前距离最小且尚未确定的节点确定下来，再用它去更新邻居。画面里橙色是当前节点，灰色是已经确定的节点，虚线描边的是有了距离、还在候选的节点。" },
    { step_id: "dijkstra-settle-A", file: "dijkstra-settle-A.mp3", text: "未确定的节点里 A 的距离最小，把它确定为 0。然后检查它的每条邻边：经由 A 到达邻居的距离若更短就更新。B 首次到达，距离 4，C 首次到达，距离 2。" },
    { step_id: "dijkstra-settle-C", file: "dijkstra-settle-C.mp3", text: "尚未确定的节点中距离最小的是 C，距离 2。它不可能再被缩短——任何别的路径都要先经过一个距离不小于它的节点。确定它之后松弛邻边：B 从 4 缩短到 3，D 首次到达，距离 10，E 首次到达，距离 12。" },
    { step_id: "dijkstra-settle-B", file: "dijkstra-settle-B.mp3", text: "尚未确定的节点中距离最小的是 B，距离 3。它不可能再被缩短——任何别的路径都要先经过一个距离不小于它的节点。确定它之后松弛邻边：D 从 10 缩短到 8。" },
    { step_id: "dijkstra-settle-D", file: "dijkstra-settle-D.mp3", text: "尚未确定的节点中距离最小的是 D，距离 8。它不可能再被缩短——任何别的路径都要先经过一个距离不小于它的节点。确定它之后松弛邻边：E 从 12 缩短到 10，F 首次到达，距离 14。" },
    { step_id: "dijkstra-settle-E", file: "dijkstra-settle-E.mp3", text: "尚未确定的节点中距离最小的是 E，距离 10。它不可能再被缩短——任何别的路径都要先经过一个距离不小于它的节点。确定它之后松弛邻边：F 从 14 缩短到 13。" },
    { step_id: "dijkstra-settle-F", file: "dijkstra-settle-F.mp3", text: "尚未确定的节点中距离最小的是 F，距离 13。它不可能再被缩短——任何别的路径都要先经过一个距离不小于它的节点。确定它之后松弛邻边：没有邻居的距离被缩短。" },
    { step_id: "dijkstra-result", file: "dijkstra-result.mp3", text: "六个节点全部确定，最终距离：A 是 0、B 是 3、C 是 2、D 是 8、E 是 10、F 是 13。把每个节点的“最后一次更新来自谁”连起来，就得到从 A 出发的最短路径树；例如到 F 的路径依次经过 A、C、B、D、E、F，长度 13。贪心成立的前提是边权非负，有负权边时要改用 Bellman-Ford。" },
  ],
  "island-biogeography": [
    { step_id: "ibg-eruption", file: "ibg-eruption.mp3", text: "1883 年 8 月，喀拉喀托火山把自己炸掉了大半，幸存的拉卡塔岛被灼热的火山灰埋了几十米——确认无一生还。此后博物学家一次次登岛点名：25 年后有 13 种留鸟，37 年后 28 种，50 年后 29 种。曲线在 30 附近躺平了。可这座岛远远没有住满，为什么停在 30？" },
    { step_id: "ibg-flows", file: "ibg-flows.mp3", text: "MacArthur 和 Wilson 换了一种看法：岛上的物种数不是爬向某个“装满”的容量，而是两股流的拔河。从大陆物种池不断有新物种渡海迁入；岛上已有的物种也在不断地局部灭绝。数量停住，只说明两股流打平了——像一个进水口和出水口同时开着的水池。" },
    { step_id: "ibg-two-curves", file: "ibg-two-curves.mp3", text: "把两股流画成 S 的函数。迁入率往下走：岛上已有 S 种，物种池 P=100 里剩下的新面孔就少一分。灭绝率往上走：种数越多，每种分到的个体越少，越容易被一场风暴抹掉。一降一升必有一交，交点就是均衡 S*=30——Wilson 当年为喀拉喀托算出的数字正是约 30。" },
    { step_id: "ibg-turnover", file: "ibg-turnover.mp3", text: "盯住交点：那里迁入和灭绝都不是零，各是约 0.9 种/年。也就是说，均衡处的岛每年送走约 0.9 种，又迎来约 0.9 种——总数纹丝不动，名单持续换血。喀拉喀托后来的普查恰好显示了这种更替：数字停在 28、29，成员却不是同一批。物种数是水位，不是名单。" },
    { step_id: "ibg-area", file: "ibg-area.mp3", text: "现在把岛缩小十倍。迁入不受影响——海峡还是那条海峡；但小岛上每个物种的种群都更小，一次歉收、一场风暴就足以清零，灭绝曲线整体变陡。交点被推向左下：均衡从 30 掉到 12。拖动右侧的面积 A，亲眼看灭绝线转动、交点滑走。" },
    { step_id: "ibg-distance", file: "ibg-distance.mp3", text: "这次把岛推远。灭绝照旧——岛还是那座岛；但渡海者按距离折损，每远 100 公里迁入率减半，迁入曲线整体压低。交点同样左移：从 30 掉到 12。两条推论合起来就是群岛的秩序：近而大的岛物种最多，远而小的最少——翻开任何一册岛屿鸟类名录，都是这个排序。" },
    { step_id: "ibg-species-area", file: "ibg-species-area.mp3", text: "理论必须交出可检验的预言。把不同面积的岛的均衡值连成曲线：A=1 时约 12 种，A=10 约 30，A=100 约 57——面积每扩大十倍，物种数大约翻一番。这正是生物地理学家在群岛上数出来的种-面积规律，S 随面积的 z 次幂增长：实测的 z 多在 0.2 到 0.35 之间，这条曲线给出 0.28 到 0.40。经验规律，就这样从迁入与灭绝的机制里被推导了出来。" },
    { step_id: "ibg-reserves", file: "ibg-reserves.mp3", text: "理论出圈了：被农田与公路切碎的森林，就是一片人造群岛。种-面积曲线立刻给出严厉的提醒——保护区缩小十倍，长期物种数减半，哪怕一棵树都没再砍。“一大还是几小”（SLOSS）因此争论了半个世纪：四个 A=25 的碎片各养约 40 种，一块 A=100 养约 57 种，孰优取决于碎片间的物种是否重复。模型不判决，但它把该问的问题亮了出来：廊道抬高迁入 λ，连片扩大压低灭绝 μ。" },
    { step_id: "ibg-boundary", file: "ibg-boundary.mp3", text: "回到拉卡塔。模型曲线在头 25 年明显高于数据——鸟不能落在光秃秃的浮石上，草和林先用几十年铺路，均衡论却把演替整个抹平了。后来的重访又发现，真实的年灭绝率比理论预言低了一个量级：普查会看漏，过客会被记成居民。它还把物种当成可互换的粒子——没有食物网，没有演化。骨架的价值在于它先回答了第一性的问题：多大的岛、多远的岛、养得起多少种。偏离骨架的部分，正是下一层生态学的开始。" },
  ],
  "linked-list-reverse": [
    { step_id: "list-intro", file: "list-intro.mp3", text: "链表依次是 1、2、3、4，末尾指向空，每个节点只知道自己的后继。反转的目标是让每个 next 指针掉头。迭代法用三个指针：prev 指向已经反转好的部分（开始时为空），curr 指向正在处理的节点，next 提前保存后继，否则指针一掉头就找不到后面的节点了。" },
    { step_id: "list-flip-1", file: "list-flip-1.mp3", text: "curr 在节点 1。先把后继保存进 next，也就是 2；再让节点 1 的 next 指向 prev，也就是 空。指针掉头之后，prev 前进到 1，curr 前进到保存好的 2。此刻已反转的前缀依次是 1，末尾指向空。" },
    { step_id: "list-flip-2", file: "list-flip-2.mp3", text: "curr 在节点 2。先把后继保存进 next，也就是 3；再让节点 2 的 next 指向 prev，也就是 1。指针掉头之后，prev 前进到 2，curr 前进到保存好的 3。此刻已反转的前缀依次是 2、1，末尾指向空。" },
    { step_id: "list-flip-3", file: "list-flip-3.mp3", text: "curr 在节点 3。先把后继保存进 next，也就是 4；再让节点 3 的 next 指向 prev，也就是 2。指针掉头之后，prev 前进到 3，curr 前进到保存好的 4。此刻已反转的前缀依次是 3、2、1，末尾指向空。" },
    { step_id: "list-flip-4", file: "list-flip-4.mp3", text: "curr 在节点 4。先把后继保存进 next，也就是 空；再让节点 4 的 next 指向 prev，也就是 3。指针掉头之后，prev 前进到 4，curr 前进到保存好的 空。next 为空，循环即将结束。" },
    { step_id: "list-result", file: "list-result.mp3", text: "curr 走到空，循环结束。prev 停在原来的尾节点 4，它就是新的头结点，返回 prev。现在链表依次是 4、3、2、1，末尾指向空。每个节点恰好被访问一次、翻转一条指针，时间 O(n)，只用了三个指针的额外空间。" },
  ],
  "logistic-growth": [
    { step_id: "logistic-data-puzzle", file: "logistic-data-puzzle.mp3", text: "1913 年，生物学家 Carlson 每小时测一次培养瓶里的酵母量。前 5 个小时它每小时都涨六成以上——照这个势头外推，第 18 小时应该超过七万。可真实的记录在 663 附近停住了。是什么按住了它？" },
    { step_id: "logistic-density-dependence", file: "logistic-density-dependence.mp3", text: "是拥挤本身。瓶里的糖被越来越多的细胞分食，人均资源随 N 下降——写成最简单的形式：人均增长率从 r 线性降到 0，即给 rN 乘上刹车项 (1−N/K)。K 就是这瓶环境长期养得起的上限。" },
    { step_id: "logistic-s-curve", file: "logistic-s-curve.mp3", text: "方程解出的 S 形曲线，用三个数就穿过全部 19 个观测：r=0.55、K=663、N₀=9.6。前段贴着指数走，后段贴着 K 放平。把右侧参数拖离这组值，曲线会当着你的面离开数据点——拟合就是这种感觉。" },
    { step_id: "logistic-inflection", file: "logistic-inflection.mp3", text: "增长最快的时刻不在种群最多的时候，而在恰好半满：N=K/2=331.5 时瞬时增长率到达最大值 rK/4=91.2，对应 t≈7.7。记住 rK/4 这个数——两步之后它会换一个身份出场。" },
    { step_id: "logistic-harvest", file: "logistic-harvest.mp3", text: "现在把模型变成决策工具：以恒定努力捕捞，每小时捞走 E·N。方程只多一项 −EN，合并后仍是 logistic——增长率降为 r−E，平衡点从 K 降到 K(1−E/r)。把右侧的捕捞强度 E 拖起来，看看种群把新家安在哪里。" },
    { step_id: "logistic-msy", file: "logistic-msy.mp3", text: "换个问题：长期每小时最多能捞走多少？平衡时的产量 Y=E·K(1−E/r) 是一条开口向下的抛物线，在 E=r/2=0.275 处到顶，最大值恰好是 rK/4=91.2——拐点处那个最大再生产速度，就是渔场的天花板。站在顶点还意味着：E 再大一点点，产量和种群就一起下坡。" },
    { step_id: "logistic-st-matthew", file: "logistic-st-matthew.mp3", text: "1944 年，29 只驯鹿被引入白令海的圣马修岛。按前 13 年的增长拟合 logistic、把 K 猜成 3000，模型预言种群平滑贴向天花板。现实是：1963 年夏数到 6000 只，随后一个严冬几乎全数饿死，1966 年只剩 42 只。不是方程算错了，是它的前提塌了——驯鹿吃光了再生要几十年的地衣，K 本身崩了，而模型假设 K 永远不变。" },
    { step_id: "logistic-skeleton", file: "logistic-skeleton.mp3", text: "回到酵母。Logistic 抓住的是密度制约这一根骨架：数据里的波动、时滞，圣马修岛那样的过冲崩溃，都是骨架上的偏离项。会用模型的意思，是同时知道它何时成立、何时失效。下一课把时间切成一年一代——同一个方程，将一路通向混沌。" },
  ],
  "monotonic-stack": [
    { step_id: "monotonic-intro", file: "monotonic-intro.mp3", text: "给定数组 [4, 2, 5, 1, 3, 6]，要为每个元素找到它右边第一个比它大的数，找不到记为 -1。暴力做法对每个元素向右扫描，是 O(n²)。单调栈的思路是：把“还在等答案”的下标存进栈，栈里对应的值保持递减。" },
    { step_id: "monotonic-visit-0", file: "monotonic-visit-0.mp3", text: "下标 0 的值是 4。栈是空的，没有谁在等它，把下标 0 压入栈。" },
    { step_id: "monotonic-visit-1", file: "monotonic-visit-1.mp3", text: "下标 1 的值是 2，不大于栈顶的 4，栈里的元素都还等不到答案。把下标 1 压入栈，栈内的值继续保持递减：[4, 2]。" },
    { step_id: "monotonic-visit-2", file: "monotonic-visit-2.mp3", text: "下标 2 的值是 5，比栈顶的 2 大。栈顶等的“右侧第一个更大值”就是它：弹出并写下答案。新的栈顶 4 也比 5 小，同样依次弹出记答案。直到栈顶不再小于 5，再把下标 2 压入。目前已确定的答案：下标 0 是 5、下标 1 是 5，其余 4 个还在等待。" },
    { step_id: "monotonic-visit-3", file: "monotonic-visit-3.mp3", text: "下标 3 的值是 1，不大于栈顶的 5，栈里的元素都还等不到答案。把下标 3 压入栈，栈内的值继续保持递减：[5, 1]。" },
    { step_id: "monotonic-visit-4", file: "monotonic-visit-4.mp3", text: "下标 4 的值是 3，比栈顶的 1 大。栈顶等的“右侧第一个更大值”就是它：弹出并写下答案。直到栈顶不再小于 3，再把下标 4 压入。目前已确定的答案：下标 0 是 5、下标 1 是 5、下标 3 是 3，其余 3 个还在等待。" },
    { step_id: "monotonic-visit-5", file: "monotonic-visit-5.mp3", text: "下标 5 的值是 6，比栈顶的 3 大。栈顶等的“右侧第一个更大值”就是它：弹出并写下答案。新的栈顶 5 也比 6 小，同样依次弹出记答案。直到栈顶不再小于 6，再把下标 5 压入。目前已确定的答案：下标 0 是 5、下标 1 是 5、下标 2 是 6、下标 3 是 3、下标 4 是 6，其余 1 个还在等待。" },
    { step_id: "monotonic-result", file: "monotonic-result.mp3", text: "数组扫描完毕。栈里还剩 [6]，它们右边再没有更大的数，答案保持 -1。最终答案是 [5, 5, 6, 3, 6, -1]。每个下标只入栈一次、出栈最多一次，整体是 O(n)，而不是暴力的 O(n²)。" },
  ],
  "predator-prey": [
    { step_id: "lv-data-pelts", file: "lv-data-pelts.mp3", text: "换一本账本：哈德逊湾公司收购毛皮的记录，1900 到 1920 年。雪兔大约十年一个峰，猞猁跟着起落，但它的峰总是晚一到两年。两条曲线互相追了二十年，谁也没甩开谁，谁也没吃光谁。是谁在驱动谁？" },
    { step_id: "lv-equations", file: "lv-equations.mp3", text: "Lotka 和 Volterra 各自写下同一对方程：雪兔没有天敌时按 rN 指数增长，被捕食拖走 aNP；猞猁吃到雪兔才增长 eaNP，否则以速率 m 饿死。四个参数，没有一个是随机数。取 r=0.55、a=0.028，从 1900 年的起点出发积分：峰的间隔约 11 年，猞猁晚约一年半——和账本对上了。" },
    { step_id: "lv-four-beats", file: "lv-four-beats.mp3", text: "为什么会绕圈？把一个周期拆成四拍：兔多，猞猁吃饱、数量上来；猞猁多，兔被压下去；兔少，猞猁挨饿、跟着下来；猞猁少，兔喘过气再起。每一拍都是上一拍的结果——因果连成环，滞后就不是巧合，而是必然：捕食者永远在追赶猎物的上一幕。" },
    { step_id: "lv-phase-plane", file: "lv-phase-plane.mp3", text: "换一种画法：横轴雪兔，纵轴猞猁，时间藏进轨迹的走向。两条零增长线把平面切成四个象限——横线 P=r/a=20 上雪兔不增不减，竖线 N=m/(ea)=34 上猞猁不增不减。刚才的四拍就是逆时针绕这两条线的交点转圈，交点 (34, 20) 恰好落在账本二十一年的平均值旁边。" },
    { step_id: "lv-neutral-cycles", file: "lv-neutral-cycles.mp3", text: "同样的参数，换三个起点：每个起点画出自己的环，既不收敛到中心，也不互相靠拢。这叫中性稳定——扰动不会被遗忘，一场瘟疫、一个暖冬，都会让种群换一条轨道绕。把右侧 N₀ 从 30 拖开，最外圈会当场换一条环给你看。" },
    { step_id: "lv-data-loop", file: "lv-data-loop.mp3", text: "把二十一年的真实记录按年份连起来，放进同一张相平面：它也在逆时针绕圈，绕的中心就在模型的均衡点附近；圈会漂、会变形——真实世界的 r 和 a 年年在变——但方向、中心、圈过的位置都是模型预言的样子。一张 1937 年整理的账本，绕着 1926 年写下的方程转。" },
    { step_id: "lv-volterra", file: "lv-volterra.mp3", text: "1920 年代，生物学家 d'Ancona 在亚得里亚海的渔市账目里发现怪事：一战期间捕捞几乎停摆，市面上鲨鱼等捕食者的占比反而从约 12% 涨到 36%。他把问题交给数学家 Volterra。答案就藏在方程里：均匀捕捞对两个物种各减去一项 qN、qP。把右侧捕捞强度 q 拖起来，看均衡点往哪边搬家。" },
    { step_id: "lv-boundary", file: "lv-boundary.mp3", text: "给雪兔补上它自己的 K：增长项换成 rN(1−N/150)。只加这一项，中性环立刻变成向内的螺旋，收进焦点 (34, 15)——环是靠“猎物无自限”这个假设撑着的。可账本里的循环持续了两百年不衰减，谜题反转：真实世界靠什么维持振荡？时滞、雪兔与食物的另一层耦合、行为反应——都在候选名单上。没有猞猁的安蒂科斯蒂岛上，雪兔照样十年一轮。" },
    { step_id: "lv-sandbox", file: "lv-sandbox.mp3", text: "旁白到此为止。r 抬高猎物等倾线，a 同时压低两条线，q 沿对角搬均衡点，N₀ 换轨道。读图口诀：横竖两条线定中心，起点定环的大小，逆时针是铁律。试试把 a 拖到 0.05 再把 q 推过 r=0.55，两种崩法长得完全不一样。下一课：不靠牙齿的战争——竞争。" },
  ],
  "rabbit-chaos": [
    { step_id: "chaos-one-generation", file: "chaos-one-generation.mp3", text: "换一种时间观：兔群一年繁殖一代，方程从微分变成迭代——明年的数量由今年一步算出。r=0.8 时它跟连续模型走同一条路，只慢半拍，最后同样贴向 K=1000。这半拍就是时滞的种子——现在看无伤大雅，对吧？" },
    { step_id: "chaos-overshoot", file: "chaos-overshoot.mp3", text: "把 r 提到 1.8：兔群冲过 K 再跌回来，振荡几年才安定。原因是时滞——今年的过剩要到明年才显形，方向盘打晚了一年。连续模型永远不会这样，它的反馈是即时的。" },
    { step_id: "chaos-period-two", file: "chaos-period-two.mp3", text: "r=2.2：振荡不再衰减，兔群锁进高一年、低一年的两年循环。它永远到不了 K，却完全可预测——这是第一次分岔。" },
    { step_id: "chaos-period-four", file: "chaos-period-four.mp3", text: "r=2.5：两年循环裂成四年循环。继续加大 r，周期以越来越快的速度翻倍：8、16、32……到 r≈2.57，翻倍塞满，秩序耗尽。" },
    { step_id: "chaos-deep", file: "chaos-deep.mp3", text: "r=2.95：轨迹再也不重复自己。注意，方程里没有一个随机数——每一步都是确定的，但整体永不循环。这就是混沌：确定性系统生出的不可预测。" },
    { step_id: "chaos-butterfly", file: "chaos-butterfly.mp3", text: "两群兔子，初始只差百万分之一只：前三十多年两条轨迹完全重合，然后彻底分道扬镳。初值的微小误差按指数放大——超过一个期限，预测就失效了。这不是测量不够准，是系统本性。" },
    { step_id: "chaos-bifurcation", file: "chaos-bifurcation.mp3", text: "把每个 r 的长期归宿都画出来：左边一条线是安定，r=2 劈成两枝，再裂成四枝，然后是混沌的噪点带——带里还嵌着突然安静的白色窗口。你刚才走过的五步，是这张图上的五条竖线；此刻的竖线停在 r=2.95。" },
    { step_id: "chaos-lorenz-shape", file: "chaos-lorenz-shape.mp3", text: "混沌不只住在兔群里。1963 年，气象学家洛伦兹在三条大气对流方程里看到同样的东西——轨迹永远绕着两翼盘旋，永不重复。你看到的交叉是三维轨迹拍进平面的投影假象，这恰好说明它活在三维里。" },
    { step_id: "chaos-lorenz-divergence", file: "chaos-lorenz-divergence.mp3", text: "还是那个 0.000001：两条洛伦兹轨迹的 x 分量，前二十多秒完全重合，之后各自绕向不同的翼。天气预报的两周上限，就是这条曲线定的——不是仪器不行，是大气本身在放大误差。" },
    { step_id: "chaos-sandbox", file: "chaos-sandbox.mp3", text: "旁白到此为止。右侧的 r 和 N₀ 现在归你：把 r 从 0.5 慢慢推到 3，找一找周期 8；进了混沌带再把 N₀ 挪一格，数一数轨迹几年后面目全非。这张图你已经会读了。" },
  ],
  "stack-brackets": [
    { step_id: "bracket-intro", file: "bracket-intro.mp3", text: "要判断这个表达式的括号是否匹配：花括号里套着方括号，方括号里再套着圆括号。规则只有一条：每个右括号必须与最近一个尚未闭合的左括号类型相同。“最近的尚未闭合”正是后进先出，所以用栈来记录还没配对的左括号，从左到右逐字符扫描。" },
    { step_id: "bracket-read-0", file: "bracket-read-0.mp3", text: "第 0 个字符是左花括号。它还没有配对对象，先压入栈顶等待。此时栈里从底到顶依次是左花括号，栈顶总是最近一个尚未闭合的左括号。" },
    { step_id: "bracket-read-1", file: "bracket-read-1.mp3", text: "第 1 个字符是左方括号。它还没有配对对象，先压入栈顶等待。此时栈里从底到顶依次是左花括号、左方括号，栈顶总是最近一个尚未闭合的左括号。" },
    { step_id: "bracket-read-2", file: "bracket-read-2.mp3", text: "第 2 个字符是左圆括号。它还没有配对对象，先压入栈顶等待。此时栈里从底到顶依次是左花括号、左方括号、左圆括号，栈顶总是最近一个尚未闭合的左括号。" },
    { step_id: "bracket-read-3", file: "bracket-read-3.mp3", text: "第 3 个字符是右圆括号。栈顶是第 2 个字符左圆括号，类型正好相同，于是弹出栈顶，两者完成配对。弹出后栈里从底到顶依次是左花括号、左方括号。" },
    { step_id: "bracket-read-4", file: "bracket-read-4.mp3", text: "第 4 个字符是右方括号。栈顶是第 1 个字符左方括号，类型正好相同，于是弹出栈顶，两者完成配对。弹出后栈里从底到顶依次是左花括号。" },
    { step_id: "bracket-read-5", file: "bracket-read-5.mp3", text: "第 5 个字符是右花括号。栈顶是第 0 个字符左花括号，类型正好相同，于是弹出栈顶，两者完成配对。弹出后栈已经空了。" },
    { step_id: "bracket-result", file: "bracket-result.mp3", text: "扫描完 6 个字符，栈恰好为空：每个右括号都找到了最近的、类型相同的左括号。返回 true。整个过程每个字符只入栈、出栈各最多一次，时间复杂度 O(n)，栈的额外空间最坏也是 O(n)。" },
  ],
});
