"""Pre-synthesize the public template narration into static audio files.

The template pages run entirely in the browser — no run, no quota, no API
call — so they cannot ask the TTS proxy for narration the way Studio does.
Recording each step once at build time keeps that boundary intact and still
gives a visitor the spoken lesson: the files ship as ordinary static assets
next to the posters, cost nothing per view, and need no sign-in.

    .venv/bin/python apps/api/scripts/generate_template_narration.py
    .venv/bin/python apps/api/scripts/generate_template_narration.py \
        predator-prey --out apps/web/public/template-narration

Reads the same frozen playbooks the export renders (data/template-previews)
and the same METAVIEW_TTS_* settings, so the recorded voice is the one in the
exported videos. Verify credentials first with scripts/check_tts.py.

Alongside the audio it regenerates ``recordedNarration.ts`` — the registry the
player reads. Shipping it as source rather than a fetched manifest keeps the
template pages at *zero* network requests (the guard in routing.test.tsx), and
it carries the exact line each file was recorded from: narration is
parameter-dependent, so a slider that rewrites a step's wording — or an edit
that lands without re-recording — leaves that step silent instead of reading
numbers that are no longer on screen.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import subprocess
import sys
import time
from pathlib import Path

import httpx

# Runnable from the repo root, not just from apps/api.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.config import get_settings  # noqa: E402
from app.infrastructure.tts import (  # noqa: E402
    WEBSOCKET_DIALECT,
    build_tts_request,
    looks_like_audio,
    post_with_retry,
    resolve_base_url,
    response_audio,
    synthesize_over_websocket,
    to_spoken,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
# The ecology pilot is the pack we narrate online; other cases can opt in by
# passing their ids explicitly.
DEFAULT_CASES = (
    "logistic-growth",
    "rabbit-chaos",
    "predator-prey",
    "competition-exclusion",
    "island-biogeography",
)


def _resolve(path_like: str) -> Path:
    path = Path(path_like)
    return path if path.is_absolute() else REPO_ROOT / path


def _transcode_for_the_web(path: Path) -> None:
    """Re-encode to 32 kbps mono — speech loses nothing, phones save data."""
    if not _has_ffmpeg():
        return
    compact = path.with_suffix(".compact.mp3")
    result = subprocess.run(
        ["ffmpeg", "-y", "-loglevel", "error", "-i", str(path),
         "-ac", "1", "-b:a", "32k", str(compact)],
        capture_output=True,
    )
    if result.returncode == 0 and compact.stat().st_size > 0:
        compact.replace(path)
    else:
        compact.unlink(missing_ok=True)


def _has_ffmpeg() -> bool:
    from shutil import which

    return which("ffmpeg") is not None


_REGISTRY_ENTRY_RE = re.compile(
    r'\{ step_id: "(?P<step>[^"]+)", file: "(?P<file>[^"]+)", text: (?P<text>"(?:[^"\\]|\\.)*") \}'
)


def _read_registry(path: Path) -> dict[str, dict[str, dict[str, str]]]:
    """Recover what each case already has on disk, so a re-run only pays for
    the lines whose wording actually changed."""
    if not path.is_file():
        return {}
    recovered: dict[str, dict[str, dict[str, str]]] = {}
    case_id: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        case_match = re.match(r'\s*"(?P<case>[a-z0-9-]+)": \[', line)
        if case_match:
            case_id = case_match.group("case")
            recovered[case_id] = {}
            continue
        entry = _REGISTRY_ENTRY_RE.search(line)
        if entry and case_id:
            recovered[case_id][entry.group("step")] = {
                "step_id": entry.group("step"),
                "file": entry.group("file"),
                "text": json.loads(entry.group("text")),
            }
    return recovered


def _write_registry(
    path: Path, recorded: dict[str, list[dict[str, str]]], *, voice: str
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by apps/api/scripts/generate_template_narration.py — do not edit.",
        "//",
        "// One entry per recorded line, carrying the text it was made from so the",
        "// player can stay silent when a parameter edit (or an un-recorded narration",
        "// change) has moved that step's wording away from the audio.",
        "",
        "export interface RecordedNarrationEntry {",
        "  step_id: string;",
        "  file: string;",
        "  text: string;",
        "}",
        "",
        f'export const RECORDED_NARRATION_VOICE = "{voice}";',
        "",
        "export const RECORDED_NARRATION: Readonly<",
        "  Record<string, readonly RecordedNarrationEntry[]>",
        "> = Object.freeze({",
    ]
    for case_id in sorted(recorded):
        lines.append(f'  "{case_id}": [')
        for entry in recorded[case_id]:
            text = json.dumps(entry["text"], ensure_ascii=False)
            lines.append(
                f'    {{ step_id: "{entry["step_id"]}", '
                f'file: "{entry["file"]}", text: {text} }},'
            )
        lines.append("  ],")
    lines += ["});", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


async def _synthesize(client: httpx.AsyncClient, settings, text: str, label: str) -> bytes:
    spoken = to_spoken(text)
    api_key = (settings.tts_api_key or settings.openai_api_key or "").strip()
    voice = settings.tts_default_voice
    if settings.tts_provider.strip().lower() == WEBSOCKET_DIALECT:
        return await synthesize_over_websocket(
            text=spoken,
            api_key=api_key,
            speaker=voice,
            resource_id=settings.tts_resource_id,
            timeout_s=settings.tts_timeout_s,
        )
    call = build_tts_request(
        provider=settings.tts_provider,
        base_url=resolve_base_url(settings.tts_provider, settings.tts_base_url),
        api_key=api_key,
        model=settings.tts_model,
        voice=voice,
        text=spoken,
        app_id=settings.tts_app_id,
        cluster=settings.tts_cluster,
        resource_id=settings.tts_resource_id,
    )
    response = await post_with_retry(client, call, label=label)
    if response.status_code >= 400:
        raise RuntimeError(f"TTS HTTP {response.status_code}: {response.text[:200]}")
    audio, audio_url = response_audio(response, label)
    if audio is None and audio_url is not None:
        fetched = await client.get(audio_url)
        audio = fetched.content
    if not audio or not looks_like_audio(audio):
        raise RuntimeError(f"{label}: response carried no recognizable audio")
    return audio


async def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("cases", nargs="*", help=f"case ids; default = {', '.join(DEFAULT_CASES)}")
    parser.add_argument("--playbooks", default="data/template-previews")
    parser.add_argument("--out", default="apps/web/public/template-narration")
    parser.add_argument(
        "--registry",
        default="apps/web/src/pages/Templates/narration/recordedNarration.ts",
        help="generated TypeScript registry the player reads",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="re-record every line instead of keeping files whose text is unchanged",
    )
    args = parser.parse_args()

    settings = get_settings()
    if not (settings.tts_api_key or settings.openai_api_key):
        raise SystemExit(
            "TTS not configured: set METAVIEW_TTS_API_KEY.\n"
            "Verify first with: .venv/bin/python apps/api/scripts/check_tts.py"
        )
    playbooks_dir = _resolve(args.playbooks)
    out_root = _resolve(args.out)
    cases = args.cases or list(DEFAULT_CASES)

    registry_path = _resolve(args.registry)
    already_recorded = _read_registry(registry_path)
    recorded: dict[str, list[dict[str, str]]] = {}
    total_lines = 0
    reused = 0
    started = time.monotonic()
    async with httpx.AsyncClient(timeout=settings.tts_timeout_s + 60) as client:
        for case_id in cases:
            playbook_path = playbooks_dir / f"{case_id}.playbook.json"
            if not playbook_path.is_file():
                raise SystemExit(
                    f"no frozen playbook for {case_id!r} at {playbook_path}\n"
                    "run: npm --workspace apps/web run template-previews:export"
                )
            script = json.loads(playbook_path.read_text(encoding="utf-8"))
            case_dir = out_root / case_id
            case_dir.mkdir(parents=True, exist_ok=True)
            previous = {} if args.force else already_recorded.get(case_id, {})

            entries = []
            print(f"{case_id}:")
            for step in script.get("steps", []):
                step_id = step["step_id"]
                text = (step.get("voiceover_text") or "").strip()
                if not text:
                    continue
                filename = f"{step_id}.mp3"
                target = case_dir / filename
                keep = (
                    not args.force
                    and target.is_file()
                    and previous.get(step_id, {}).get("text") == text
                )
                if keep:
                    reused += 1
                else:
                    audio = await _synthesize(client, settings, text, f"{case_id}/{step_id}")
                    target.write_bytes(audio)
                    _transcode_for_the_web(target)
                size_kb = target.stat().st_size / 1000
                print(f"  {'·' if keep else '✓'} {step_id:<28} {size_kb:5.0f} KB")
                entries.append({"step_id": step_id, "file": filename, "text": text})
                total_lines += 1

            recorded[case_id] = entries

    _write_registry(registry_path, recorded, voice=settings.tts_default_voice)
    elapsed = time.monotonic() - started
    print(
        f"\n{total_lines} line(s) across {len(cases)} case(s) → {out_root}"
        f"  ({reused} reused, {elapsed:.0f}s)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
